13:47:46,317 ERROR 
13:50:14,744 ERROR 
13:52:52,534 ERROR Error
Traceback (most recent call last):
  File "/home/pi/CMS/test.py", line 18, in main
    error()
  File "/home/pi/CMS/test.py", line 7, in error
    raise TypeError
TypeError
2022:53:D:13:53:50,359 ERROR Error
Traceback (most recent call last):
  File "/home/pi/CMS/test.py", line 18, in main
    error()
  File "/home/pi/CMS/test.py", line 7, in error
    raise TypeError
TypeError
2022:54:10/05/22:13:54:35,373 ERROR Error
Traceback (most recent call last):
  File "/home/pi/CMS/test.py", line 18, in main
    error()
  File "/home/pi/CMS/test.py", line 7, in error
    raise TypeError
TypeError
10/05/22:13:55:09,980 ERROR Error
Traceback (most recent call last):
  File "/home/pi/CMS/test.py", line 18, in main
    error()
  File "/home/pi/CMS/test.py", line 7, in error
    raise TypeError
TypeError
10/05/22  13:55:42,65 ERROR Error
Traceback (most recent call last):
  File "/home/pi/CMS/test.py", line 18, in main
    error()
  File "/home/pi/CMS/test.py", line 7, in error
    raise TypeError
TypeError
